# 02.07 Modules: Forex

> https://docs.openbb.co/sdk/guides/intros/forex

In [1]:
from openbb_terminal.sdk import openbb
import pandas as pd
#%matplotlib inline

Forecasting Toolkit is disabled. To use the Forecasting features please install the toolkit following the instructions here: https://my.openbb.co/app/sdk/installation

Portfolio Optimization Toolkit is disabled. To use the Optimization features please install the toolkit following the instructions here: https://my.openbb.co/app/sdk/installation

In [2]:
currency_pair = openbb.forex.load(
    from_symbol='USD',
    to_symbol='EUR',
    start_date = '2022-01-01',
    interval = '1week')

currency_pair.head(3)

               Open     High      Low    Close  Adj Close  Volume
date
2022-01-01  0.87910  0.88704  0.87905  0.88520    0.88520       0
2022-01-08  0.88000  0.88587  0.87080  0.87282    0.87282       0
2022-01-15  0.87593  0.88478  0.87454  0.88388    0.88388       0

[Average True Range](https://docs.openbb.co/sdk/guides/intros/forex#average-true-range)

In [3]:
weekly_atr = openbb.ta.atr(data = currency_pair, window = 4)
currency_pair = currency_pair.join(weekly_atr)

currency_pair.tail(1)

              Open    High     Low   Close  Adj Close  Volume    ATRe_4
date
2023-06-03  0.9322  0.9322  0.9322  0.9322     0.9322       0  0.009434

[Forward Rates](https://docs.openbb.co/sdk/guides/intros/forex#average-true-range)

In [4]:
fwd_eurusd = openbb.forex.fwd('USD', 'EUR')

fwd_eurusd

                   Ask      Bid      Mid    Points
Expiration
Overnight      1.07125  1.07093  1.07109     1.680
Tomorrow Next  1.07114  1.07082  1.07098     0.582
Spot Next      1.07114  1.07082  1.07098     0.585
One Week       1.07150  1.07117  1.07133     4.125
Two Weeks      1.07193  1.07160  1.07177     8.450
Three Weeks    1.07234  1.07201  1.07217    12.540
One Month      1.07295  1.07262  1.07279    18.660
Two Months     1.07486  1.07452  1.07469    37.660
Three Months   1.07661  1.07626  1.07644    55.160
Four Months    1.07839  1.07802  1.07821    72.860
Five Months    1.08008  1.07971  1.07990    89.780
Six Months     1.08160  1.08123  1.08142   104.970
Seven Months   1.08410  1.08368  1.08389   129.680
Eight Months   1.08545  1.08503  1.08524   143.240
Nine Months    1.08675  1.08633  1.08654   156.190
Ten Months     1.08833  1.08791  1.08812   171.980
Eleven Months  1.08947  1.08907  1.08927   183.470
One Year       1.09065  1.09023  1.09044   195.200
Two Years      1.10182  1.10110  1.10146   305.400
Three Years    1.11134  1.11002  1.11068   397.620
Four Years     1.12233  1.12001  1.12117   502.540
Five Years     1.13260  1.13028  1.13144   605.150
Six Years      1.14328  1.14146  1.14237   714.500
Seven Years    1.15378  1.15146  1.15262   817.000
Ten Years      1.18498  1.17966  1.18232  1114.000

Not all currency pairs will have the same length of term structure.

In [6]:
fwd_jpyeur = openbb.forex.fwd('JPY', 'EUR')
fwd_pairs = fwd_jpyeur.join(fwd_jpyeur, on = ['Expiration'], lsuffix = ' JPY/EUR', rsuffix=' USD/EUR')
fwd_pairs

,Ask JPY/EUR,Bid JPY/EUR,Mid JPY/EUR,Points JPY/EUR,Ask USD/EUR,Bid USD/EUR,Mid USD/EUR,Points USD/EUR
Expiration,,,,,,,,
Overnight,149.943,149.895,149.919,-4.205,149.943,149.895,149.919,-4.205
Tomorrow Next,149.943,149.895,149.919,-1.375,149.943,149.895,149.919,-1.375
Spot Next,149.943,149.895,149.919,-1.385,149.943,149.895,149.919,-1.385
One Week,149.943,149.894,149.918,-9.700,149.943,149.894,149.918,-9.700
Two Weeks,149.942,149.893,149.918,-19.420,149.942,149.893,149.918,-19.420
Three Weeks,149.941,149.892,149.916,-29.700,149.941,149.892,149.916,-29.700
One Month,149.939,149.891,149.915,-43.560,149.939,149.891,149.915,-43.560
Two Months,149.934,149.886,149.910,-91.535,149.934,149.886,149.910,-91.535
Three Months,149.930,149.882,149.906,-138.020,149.930,149.882,149.906,-138.020
Four Months,149.925,149.877,149.901,-185.490,149.925,149.877,149.901,-185.490
Five Months,149.920,149.872,149.896,-234.865,149.920,149.872,149.896,-234.865
Six Months,149.915,149.867,149.891,-282.775,149.915,149.867,149.891,-282.775
Seven Months,149.910,149.861,149.885,-339.840,149.910,149.861,149.885,-339.840
Eight Months,149.905,149.857,149.881,-383.995,149.905,149.857,149.881,-383.995
Nine Months,149.901,149.852,149.877,-428.895,149.901,149.852,149.877,-428.895
Ten Months,149.896,149.847,149.872,-478.055,149.896,149.847,149.872,-478.055
Eleven Months,149.892,149.843,149.867,-521.510,149.892,149.843,149.867,-521.510
One Year,149.887,149.839,149.863,-565.875,149.887,149.839,149.863,-565.875
Two Years,149.842,149.793,149.817,-1020.440,149.842,149.793,149.817,-1020.440